apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: atinfer-eks-cluster
  region: us-west-2

nodeGroups:
  - name: atinfer-nodegroup-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: atinfer-nodegroup-2
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      #publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      publicKeyPath: ~/.ssh/id_rsa.pub